# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

     # Runs a single command using the runners shell
      - name: Composer validate/update
        run: |
          curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
          composer update
          
      - name: Directory Permissions
        run: chmod -R 777 ./    
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build laravel
        id: build-php-image
        run: |
          docker build -t app .
          docker tag app:latest 876828831662.dkr.ecr.ap-southeast-1.amazonaws.com/app:latest
          docker push 876828831662.dkr.ecr.ap-southeast-1.amazonaws.com/app:latest
      - name: Build nginx
        id: build-nginx-image
        run: |
          docker build . -f Dockerfile_Nginx -t nginx
          docker tag nginx:latest 876828831662.dkr.ecr.ap-southeast-1.amazonaws.com/nginx:latest
          docker push 876828831662.dkr.ecr.ap-southeast-1.amazonaws.com/nginx:latest          
      - name: Download task definition
        run: |
            aws ecs describe-task-definition --task-definition MTR --query taskDefinition > task-definition.json    
      - name: Fill in the new app image ID in the Amazon ECS task definition
        id: app-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: app
          image: 876828831662.dkr.ecr.ap-southeast-1.amazonaws.com/app:latest
        env:
          AWS_DEFAULT_REGION: ap-southeast-1
          AWS_REGION: ap-southeast-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Fill in the new nginx image ID in the Amazon ECS task definition
        id: web-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: nginx
          image: 876828831662.dkr.ecr.ap-southeast-1.amazonaws.com/nginx:latest
        env:
          AWS_DEFAULT_REGION: ap-southeast-1
          AWS_REGION: ap-southeast-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.web-task-def.outputs.task-definition }}
          service: MSR
          cluster: MCR
          wait-for-service-stability: true